---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readxl)
library(data.table)
library(dplyr)
library(ggplot2)
library(purrr)
library(showtext)

#設定檔案路徑，假設所有 Excel 檔案都在這個資料夾
folder_path <- "C:/Users/user/Desktop/運籌/普悠瑪客運"

#取得所有 Excel 檔案名稱
file_list <- list.files(path = folder_path, pattern = "\\.xlsx$", full.names = TRUE)

#讀取每個 Excel 檔案，並提取欄位名稱
df_list <- purrr::map(file_list, ~ read_excel(.))

#取得所有檔案中的欄位名稱，並找到所有欄位的交集
common_cols <- Reduce(intersect, lapply(df_list, names))

#只選取每個資料框中存在的共同欄位，並合併
df_list <- purrr::map(df_list, ~ .[common_cols])

#使用 bind_rows() 合併所有資料框
combined_df <- bind_rows(df_list)

#檢視合併後的結果
head(combined_df)
table(combined_df$路線編號)
table(combined_df$上車交易日期)

#上車時間日期
combined_df$上車日期 <- as.Date(combined_df$上車交易日期, format = "%Y%m%d")
combined_df$上車年 <- format(combined_df$上車日期, "%Y")
combined_df$上車月 <- format(combined_df$上車日期, "%m")
combined_df$上車日 <- format(combined_df$上車日期, "%d")

#下車時間日期
combined_df$下車日期 <- as.Date(combined_df$下車交易日期, format = "%Y%m%d")
combined_df$下車年 <- format(combined_df$下車日期, "%Y")
combined_df$下車月 <- format(combined_df$下車日期, "%m")
combined_df$下車日 <- format(combined_df$下車日期, "%d")

#以路線區分
route9801 <- combined_df[which(combined_df$路線編號 == "9801"),]
route9803 <- combined_df[which(combined_df$路線編號 == "9803"),]
route9805 <- combined_df[which(combined_df$路線編號 == "9805"),]
route9806 <- combined_df[which(combined_df$路線編號 == "9806"),]

#以年區分
year2022 <- combined_df[which(combined_df$上車年 == "2022"),]
year2023 <- combined_df[which(combined_df$上車年 == "2023"),]
year2024 <- combined_df[which(combined_df$上車年 == "2024"),]


#計算
year_count <- combined_df %>% count(上車年, name = "數量") %>% 
  filter(!is.na(上車年)) %>% mutate(上車年 = as.numeric(上車年) - 1911)

#查看結果
print(year_count)
```



```{r}
png("110-112年乘車人次折線圖.png",
    width = 980,
    height = 540,
    unit = "px",
    family = "kai")

#繪圖
## 字型設定: 標楷體
library(grDevices)
windowsFonts(kai = windowsFont("DFKai-SB"))
par(family = "kai", mar = c(5, 10, 8, 6))
plot(x = year_count$上車年,
     y = year_count$數量,
     type = "o",
     main = "110-112年乘車人次折線圖",
     xlab = "",
     ylab = "",
     lwd = 2,
     pch = 16,
     cex.main = 2,
     cex.lab = 2,
     cex.axis = 1.5,
     cex = 1.5,
     ylim = c(0, max(na.omit(year_count$數量)) * 1.1),
     xaxt = "n",
     yaxt = "n",
     bty = "n")

# x 軸
axis(side = 1, 
     at = seq(min(year_count$上車年), max(year_count$上車年)), 
     labels = year_count$上車年, 
     cex.axis = 1.5)

# y 軸
axis(side = 2, 
     las = 1, 
     cex.axis = 1.5, 
     line = 0)

mtext("年份", side = 1, line = 3, cex = 1.5)
mtext("乘車人次", side = 2, line = 7, cex = 1.5)

##加上網格線
grid()

text(x = year_count$上車年,
     y = year_count$數量,
     labels = year_count$數量,
     pos = 3, 
     offset = 1.2, 
     cex = 1.2)

dev.off()
```


```{r}

```

